@echo off
REM GotIt First-time Setup — creates ~/.gotit/.env configuration
echo ============================================
echo  GotIt Setup
echo ============================================

set GOTIT_DIR=%USERPROFILE%\.gotit
if not exist "%GOTIT_DIR%" mkdir "%GOTIT_DIR%"

if exist "%GOTIT_DIR%\.env" (
    echo.
    echo Config already exists: %GOTIT_DIR%\.env
    echo Edit it manually or delete it to re-run setup.
    echo.
    goto :show_config
)

echo.
echo Creating config at: %GOTIT_DIR%\.env
echo.

set /p LLM_PROVIDER="LLM Provider (openai): " || set LLM_PROVIDER=openai
set /p LLM_API_KEY="API Key: "
set /p LLM_MODEL="Model name (e.g. gpt-4o): "
set /p LLM_BASE_URL="API Base URL (leave empty for default): "
set /p ES_PATH="Everything CLI path (D:\03_Tools\Everything\es.exe): " || set ES_PATH=es.exe

(
echo # GotIt Configuration
echo # Generated by setup script
echo.
echo # --- LLM ---
echo GOTIT_LLM__PROVIDER=%LLM_PROVIDER%
echo GOTIT_LLM__API_KEY=%LLM_API_KEY%
echo GOTIT_LLM__MODEL=%LLM_MODEL%
if defined LLM_BASE_URL echo GOTIT_LLM__BASE_URL=%LLM_BASE_URL%
echo.
echo # --- Search ---
echo GOTIT_SEARCH__EVERYTHING_PATH=%ES_PATH%
echo GOTIT_SEARCH__MAX_RESULTS=20
echo.
echo # --- Server ---
echo GOTIT_SERVER__HOST=127.0.0.1
echo GOTIT_SERVER__PORT=8765
) > "%GOTIT_DIR%\.env"

echo.
echo Config saved to: %GOTIT_DIR%\.env

:show_config
echo.
echo Current config:
echo ----------------------------------------
type "%GOTIT_DIR%\.env"
echo ----------------------------------------
echo.
echo You can edit this file anytime: %GOTIT_DIR%\.env
echo.
pause
